In [1]:
import tensorflow as tf
import numpy as np

2023-09-08 22:18:09.026560: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-08 22:18:09.235242: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-08 22:18:09.236718: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-08 22:18:11.012447: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
tf.random.set_seed(5)
#creates a reproducible sequence of tensors across multiple calls
print(tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=10,
    name=None
))
print(tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=10,
    name=None
))
print(tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=10,
    name=None
))
print(tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=10,
    name=None
))

tf.Tensor(
[[0.09164894 0.95672214]
 [0.02972937 0.7234143 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.30528796 0.72403336]
 [0.8724446  0.25781178]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.92122746 0.8122997 ]
 [0.95292866 0.888075  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2430352  0.60351646]
 [0.00696754 0.38306487]], shape=(2, 2), dtype=float32)


In [3]:
tf.random.set_seed(5)
#creates a reproducible sequence of tensors across multiple calls
print(tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=10,
    name=None
))
print(tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=10,
    name=None
))
print(tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=10,
    name=None
))
print(tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=10,
    name=None
))

tf.Tensor(
[[0.09164894 0.95672214]
 [0.02972937 0.7234143 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.30528796 0.72403336]
 [0.8724446  0.25781178]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.92122746 0.8122997 ]
 [0.95292866 0.888075  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.2430352  0.60351646]
 [0.00696754 0.38306487]], shape=(2, 2), dtype=float32)


In [4]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([2,3,4])
print(tensor_one_d)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [6]:
tensor_two_d = tf.constant([[2,3,4,5],[2,3,2,1],[9,8,0,1]])
print(tensor_two_d)

tf.Tensor(
[[2 3 4 5]
 [2 3 2 1]
 [9 8 0 1]], shape=(3, 4), dtype=int32)


In [7]:
tensor_three_d = tf.constant([[[2,3,4],[2,3,2],[9,8,0]],[[2,3,4],[2,3,2],[9,8,0]]])
print(tensor_three_d)

tf.Tensor(
[[[2 3 4]
  [2 3 2]
  [9 8 0]]

 [[2 3 4]
  [2 3 2]
  [9 8 0]]], shape=(2, 3, 3), dtype=int32)


In [8]:
print(tensor_three_d.shape)
print(tensor_three_d.ndim)

(2, 3, 3)
3


In [9]:
tensor_one_d = tf.constant([2,3,4.2],dtype=tf.float32)
print(tensor_one_d)
casted_tensor = tf.cast(tensor_one_d,dtype = tf.int32)
print(casted_tensor)

tf.Tensor([2.  3.  4.2], shape=(3,), dtype=float32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [10]:
np_array = np.array([2,3,4])
print(np_array)
converted = tf.convert_to_tensor(np_array)
print(converted)

[2 3 4]
tf.Tensor([2 3 4], shape=(3,), dtype=int64)


In [11]:
#Diagonal Matrix creation
eye_tensor = tf.eye(
    num_rows=3,num_columns=None,batch_shape = [2,2],dtype=tf.dtypes.bool,name=None
)
print(eye_tensor)

tf.Tensor(
[[[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]


 [[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]], shape=(2, 2, 3, 3), dtype=bool)


In [12]:
tf.fill(
    [3,3],1,name=None
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [13]:
tf.ones(
    [3,3],dtype = tf.dtypes.float32,name  = None
)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [14]:
tf.ones_like(tensor_two_d,dtype = tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [15]:
tf.zeros(
    [3,3],dtype = tf.dtypes.float32,name  = None
)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [16]:
tf.zeros_like(tensor_two_d,dtype = tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [17]:
tf.rank(tensor_two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
tf.size(tensor_two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [19]:
tf.random.normal(
    [2,2],
    mean = 100.0,
    stddev= 1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[99.819695, 99.04971 ],
       [99.96036 , 99.25746 ]], dtype=float32)>

In [20]:
tf.random.uniform(
    [2,2],
    minval = 0,
    maxval= None,
    dtype=tf.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7017075 , 0.04336786],
       [0.5604572 , 0.12203383]], dtype=float32)>

In [21]:
tf_indexed = tf.constant([2,3,4,5,6,2])
print(tf_indexed[1:4:2])

tf.Tensor([3 5], shape=(2,), dtype=int32)


In [22]:
tensor_two_d

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [2, 3, 2, 1],
       [9, 8, 0, 1]], dtype=int32)>

In [23]:
print(tensor_two_d[0:2,:])
print(tensor_two_d[2,:])
print(tensor_two_d[0:2,...])
#rows,cols
#extend this for 3d a,b,c

tf.Tensor(
[[2 3 4 5]
 [2 3 2 1]], shape=(2, 4), dtype=int32)
tf.Tensor([9 8 0 1], shape=(4,), dtype=int32)
tf.Tensor(
[[2 3 4 5]
 [2 3 2 1]], shape=(2, 4), dtype=int32)


In [24]:
print(tensor_two_d)

tf.Tensor(
[[2 3 4 5]
 [2 3 2 1]
 [9 8 0 1]], shape=(3, 4), dtype=int32)


In [25]:
#tf.math
print(tf.abs([2,-2]))
#print(tf.math.max(tensor_two_d))
print(tf.math.argmax(tensor_two_d))
print(tf.math.argmax(tensor_two_d,1))

tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([2 2 0 0], shape=(4,), dtype=int64)
tf.Tensor([3 1 0], shape=(3,), dtype=int64)


In [26]:
x1 = tf.constant([2,3,4,5,6,7],dtype=tf.float32)
x2 = tf.constant([1],dtype=tf.float32)

print(tf.math.multiply(x1,x2))
#stretching occured here

tf.Tensor([2. 3. 4. 5. 6. 7.], shape=(6,), dtype=float32)


In [27]:
#argmax returns the index of maximum
tensor_two_d

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [2, 3, 2, 1],
       [9, 8, 0, 1]], dtype=int32)>

In [52]:
print(tf.math.reduce_sum(
    tensor_two_d,
    keepdims=True
))
print(tf.math.reduce_max(
    tensor_two_d,
    keepdims=True
))
print(tf.math.reduce_sum(
    tensor_two_d,
    axis = 1,
    keepdims=True
))
print(tf.math.reduce_sum(
    tensor_two_d,
    axis = 0,
    keepdims=True
))
#axis = 1 --> rows sum
#axis = 0 --> cols sum
#adds all elements of the tensor

tf.Tensor([[40]], shape=(1, 1), dtype=int32)
tf.Tensor([[9]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[14]
 [ 8]
 [18]], shape=(3, 1), dtype=int32)
tf.Tensor([[13 14  6  7]], shape=(1, 4), dtype=int32)


In [29]:
print(tf.math.top_k( tensor_one_d,k=2))

TopKV2(values=<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.2, 3. ], dtype=float32)>, indices=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>)


In [30]:
#Linear Algebra
#matrix multiplication  ---> @
print(tf.transpose(tensor_one_d))

tf.Tensor([2.  3.  4.2], shape=(3,), dtype=float32)


In [31]:
tf.linalg.matmul(tensor_two_d,tensor_two_d,transpose_a=False,transpose_b=True,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type=None,name=None)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  26,  47],
       [ 26,  18,  43],
       [ 47,  43, 146]], dtype=int32)>

In [49]:
#matrix multiplication for higher dimensions
#x1[0]*x2[0,:] -> Batch multiplication
#sparse tensors(mostly zeroes) ->Faster computations
mat = tf.constant([[1,2,3]
                   ,[-1,1,2],
                   [-2,1,2]],dtype = tf.float32)
print(tf.linalg.band_part(mat,-1,0))
#band[i,j,k....] = in_band(m,n)*input[i,j,k....]
#in_band(m,n) = (num_lower<0 || (m-n)<=num_lower)&&(num_upper<0 || (n-m)<=num_upper)
#band_part(0,-1) ---> Upper Triangular
#band_part(-1,0) ---> Lower Triangular
#band_part(0,0) ---> Diagonal

tf.Tensor(
[[ 1.  0.  0.]
 [-1.  1.  0.]
 [-2.  1.  2.]], shape=(3, 3), dtype=float32)


In [50]:
#tf.linalg.svd --> Eliminating useless information
s,u,v = tf.linalg.svd(mat)
print(s,u,v)

tf.Tensor([4.843616   2.3519523  0.08778124], shape=(3,), dtype=float32) tf.Tensor(
[[-0.69566053  0.6916316   0.19417119]
 [-0.48963025 -0.25871757 -0.8326628 ]
 [-0.5256604  -0.6743227   0.5186232 ]], shape=(3, 3), dtype=float32) tf.Tensor(
[[ 0.17451645  0.9774834  -0.11861754]
 [-0.49686253  0.19142523  0.8464536 ]
 [-0.8501009   0.08878343 -0.5190817 ]], shape=(3, 3), dtype=float32)
