In [2]:
import numpy as np

In [7]:
A = np.array([[2,6,5,2],
             [2,-2,2,3],
             [1,5,4,0]])
B = np.array([[2,9,0,3,0],
             [3,6,8,-2,2],
             [1,3,5,0,1],
             [3,0,2,0,5]])
print("Matmul : ")
print(np.matmul(A,B))

#einsum is like matmul
print("Einsum : ")
print(np.einsum("ij,jk -> ik",A,B))
print(np.einsum("ij,ij -> ij",A,A))

Matmul : 
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]
Einsum : 
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]
[[ 4 36 25  4]
 [ 4  4  4  9]
 [ 1 25 16  0]]


In [8]:
#Transpose
np.einsum("ij->ji",A)

array([[ 2,  2,  1],
       [ 6, -2,  5],
       [ 5,  2,  4],
       [ 2,  3,  0]])

In [10]:
#Batch Multiplication
A1 = np.array([[[2,6,5,2],
             [2,-2,2,3],
             [1,5,4,0]],
             [[2,6,5,2],
             [2,-2,2,3],
             [1,5,4,0]]])
B1 = np.array([[[2,9,0,3,0],
             [3,6,8,-2,2],
             [1,3,5,0,1],
             [3,0,2,0,5]],
             [[2,9,0,3,0],
             [3,6,8,-2,2],
             [1,3,5,0,1],
             [3,0,2,0,5]]])
np.einsum("bij,bjk -> bik",A1,B1)

array([[[33, 69, 77, -6, 27],
        [ 9, 12,  0, 10, 13],
        [21, 51, 60, -7, 14]],

       [[33, 69, 77, -6, 27],
        [ 9, 12,  0, 10, 13],
        [21, 51, 60, -7, 14]]])

In [11]:
#Sum
np.einsum("bij -> ",A1)

60

In [12]:
np.einsum("ij -> j",A)

array([ 5,  9, 11,  5])