In [1]:
import tensorflow as tf
#tensorflow API Documentation for more examples

2023-09-09 10:08:25.604037: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-09 10:08:25.839034: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-09 10:08:25.840822: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-09 10:08:28.204977: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
x = tf.constant([1,2,3,4])
#expands dimension
x1 = tf.expand_dims(x,axis = 0)
#axis = -1
#reduces dimension of val =1
x2 = tf.squeeze(x1,axis = 0)
print(x)
print(x1)
print(x2)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [3]:
#reshape -> no of elements should match
t = [[1,2,3,4],
     [2,3,4,5]]
print(tf.reshape(t,[2,2,2]))
print(tf.reshape(t,[8,]))
print(tf.reshape(t,[-1,]))

tf.Tensor(
[[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor([1 2 3 4 2 3 4 5], shape=(8,), dtype=int32)
tf.Tensor([1 2 3 4 2 3 4 5], shape=(8,), dtype=int32)


In [4]:
#concat
#axis = 0 along outer axis
#axis = 1 along next inner axis and so on
t1 = tf.constant([[[1,2,3,4],
     [2,3,4,5]]])
t2 = tf.constant([[[1,0,0,0],
     [2,3,4,5]]])
print(tf.concat([t1,t2],axis = 0))
print(tf.concat([t1,t2],axis = 1))
print(tf.concat([t1,t2],axis = 2))

print(tf.concat([t1,t2],axis = 0).shape)
print(tf.concat([t1,t2],axis = 1).shape)
print(tf.concat([t1,t2],axis = 2).shape)

tf.Tensor(
[[[1 2 3 4]
  [2 3 4 5]]

 [[1 0 0 0]
  [2 3 4 5]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[[1 2 3 4]
  [2 3 4 5]
  [1 0 0 0]
  [2 3 4 5]]], shape=(1, 4, 4), dtype=int32)
tf.Tensor(
[[[1 2 3 4 1 0 0 0]
  [2 3 4 5 2 3 4 5]]], shape=(1, 2, 8), dtype=int32)
(2, 2, 4)
(1, 4, 4)
(1, 2, 8)


In [5]:
#stack
t11 = tf.constant([[[1,2,3,4],
     [2,3,4,5]]])
t21 = tf.constant([[[1,0,0,0],
     [2,3,4,5]]])
print(tf.stack([t11,t21],axis = 0))
print(tf.stack([t11,t21],axis = 1))
print(tf.stack([t11,t21],axis = 2))

print(tf.stack([t11,t21],axis = 0).shape)
print(tf.stack([t11,t21],axis = 1).shape)
print(tf.stack([t11,t21],axis = 2).shape)

tf.Tensor(
[[[[1 2 3 4]
   [2 3 4 5]]]


 [[[1 0 0 0]
   [2 3 4 5]]]], shape=(2, 1, 2, 4), dtype=int32)
tf.Tensor(
[[[[1 2 3 4]
   [2 3 4 5]]

  [[1 0 0 0]
   [2 3 4 5]]]], shape=(1, 2, 2, 4), dtype=int32)
tf.Tensor(
[[[[1 2 3 4]
   [1 0 0 0]]

  [[2 3 4 5]
   [2 3 4 5]]]], shape=(1, 2, 2, 4), dtype=int32)
(2, 1, 2, 4)
(1, 2, 2, 4)
(1, 2, 2, 4)


In [6]:
#padding
t13 = tf.constant([[1,2,3,4],
     [2,3,4,5]])
t23 = tf.constant([[1,0,0,0],
     [2,3,4,5]])
pad = [[1,1],
       [2,2]]
#pad [top,down]
#    [left,right]
print(tf.pad(t13,pad,"CONSTANT"))

tf.Tensor(
[[0 0 0 0 0 0 0 0]
 [0 0 1 2 3 4 0 0]
 [0 0 2 3 4 5 0 0]
 [0 0 0 0 0 0 0 0]], shape=(4, 8), dtype=int32)


In [7]:
#gather
params = tf.constant(['p0','p1','p2','p3','p4','p5'])
params[0:4]
print(tf.gather(params,[0,3,5],axis = 0))

tf.Tensor([b'p0' b'p3' b'p5'], shape=(3,), dtype=string)


In [11]:
print(tf.gather(t13,[0,1],axis = 0))
print(tf.gather(t13,[0,1],axis = 1))

tf.Tensor(
[[1 2 3 4]
 [2 3 4 5]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[1 2]
 [2 3]], shape=(2, 2), dtype=int32)


In [16]:
indices = [[0,1],]
indices1 = [[0,0,1],]
print(tf.gather_nd(t13,indices))
print(tf.gather_nd(t11,indices1))
#batch_dims = 1 --> making it aware of batches

tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)


In [18]:
#we may have datas with unequal no of columns
#Racgged tensors deal with them
tensor_2d = [[1,2],
             [3],
             [1,2,3]]
tensor_ragged = tf.ragged.constant(tensor_2d)
print(tensor_ragged.shape)

(3, None)


In [19]:
#tf.sparse.SparseTensor
#working with tensors having mostly zeroes
tf_sparse = tf.sparse.SparseTensor([[1,1],[3,3]],[1,5],[4,4])

In [20]:
print(tf.sparse.to_dense(tf_sparse))

tf.Tensor(
[[0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 5]], shape=(4, 4), dtype=int32)


In [22]:
#String tensors
tensor_string = tf.constant(["hello","i am","string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'string'], shape=(3,), dtype=string)


In [36]:
tf.strings.join(tensor_string,separator = " ")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello i am string'>

In [37]:
x_var = tf.Variable(tensor_string,trainable=True)
#x_var[0] = "Hi"
print(x_var)

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'hello', b'i am', b'string'], dtype=object)>


In [39]:
#with tf.device('GPU:0'):
#   write code here
with tf.device('GPU:0'):
    x_1 = tf.constant([1,3,4])

print(x_1.device)

/job:localhost/replica:0/task:0/device:CPU:0
